### PR TITLE
Fixed Arrow Positioning when button close to the top

### PR DESCRIPTION
**Pull request by marcoacfilho**
**Release Type:** *Breaking Changes* 

Fixes https://x-team-internal.atlassian.net/browse/XP-2946

## Description

Created story to better test the ListExclusionFormPopup in a real use case, and fixed arrow positioning.

## Checklist

- [x] set yourself as an assignee
- [x] set appropriate labels for a PR (`In Review` or `In Progress` depending on its status)
- [x] move respective JIRA issue to the `IN REVIEW` column
- [x] make sure your code lints (`npm run lint`)
- [x] Flow typechecks passed (`npm run flow`)
- [x] Snapshots tests passed (`npm run jest`)
- [x] component's documentation (`.stories.js` file) is changed or added accordingly to reflect any new or updated use cases or variants usage
- [x] if any snapshots have been changed, verify that component still works and looks as expected and update the changed snapshot
- [x] **manually tested the app** by running it in several different browsers (Firefox, Chrome, Opera, Safari, MS IE/Edge, etc.) and checked nothing is broken and operates as expected!

## Related PRs

xp_ui | [XP](https://github.com/x-team/xp-ui/pull/375)
xp_ui | [XP](https://github.com/x-team/xp-ui/pull/374)

## Steps to Test or Reproduce

1. Search for ListExclusionFormPopup 
2. Test the different use cases 

## Impacted Areas in Application

- `ui/ListExclusionFormPopup.js`

## Screenshots

image

### CODE REVIEW

**Comment by nicksp** [comment]
@marcoacfilho Any change to the `xp-ui` repo requires rebuilding the project with: `npm run build`. We have a ticket to automate that, but right now that's required. Please keep this in mind for future changes 😄 Fixed in https://github.com/x-team/xp-ui/pull/376/commits/c9f1909045900c19ae29cd4372e93c3a2c87d83b

**Comment by nicksp** [comment]
@marcoacfilho While testing I noticed a glitch with positioning. Is this expected? Just wondering if that worked for you:

Screenshot 2019-04-02 at 20 28 10

And here's how it looks in integration. Seems like it's the same issue as it was before with the top applicant badge.

Screenshot 2019-04-02 at 20 33 14

**Comment by bernardodiasc** [comment]
hey @nicksp and @marcoacfilho, I fixed the positioning calculation at https://github.com/x-team/xp-ui/pull/376/commits/0297086647c43536b327642b956d48ecc70b70b5

**Comment by nicksp** [comment]
@bernardodiasc Thanks for addressing this remaining part!

**Pull request merged**
