### PR TITLE
Replace tabs with GenericTab

### PR DESCRIPTION
**Pull request by bernardorubin**
**Release Type:** *Dev Improvements* 

Fixes https://github.com/x-team/xp/issues/1820

## Description

With this clean up we want to completely replace the old Tabs with the new generic Tab, and then rename it back to Tabs.

## Checklist

**Before submitting a pull request,** please make sure the following is done:

- [x] set yourself as an assignee
- [x] set appropriate labels for a PR (`In Review` or `In Progress` depending on its status)
- [x] fill out `Is a breaking change` and `Release Type Reason` (if required) fields for the ticket. 
- [x] make sure your code lints (`npm run lint`)
- [ ] Flow typechecks passed (`npm run flow`) More details on section below 👇🏼
- [x] Snapshots tests passed (`npm run jest`)
- [x] if any snapshots have been changed, verify that component still works and looks as expected and update the changed snapshot
- [x] **manually tested the app** by running it in several different browsers (Firefox, Chrome, Opera, Safari, MS IE/Edge, etc.) and checked nothing is broken and operates as expected!

## Related PRs

branch | PR
------ | ------
gh-issue-1820-replace-tabs-with-generic-tab | [XP](https://github.com/x-team/xp/pull/1908)

## Steps to Test or Reproduce

1. `npm start`
2. Stories behavior for `Tabs` should work properly
3. Stories behavior for `ListsEditor` should work properly

## Impacted Areas in Application

Components that use the Tabs component

I spent most time making `ListsEditor` component which was not mentioned on the issue to work with the new created `GenericTab` which has now been renamed to `Tabs` and old `Tabs` was deleted as the task requested.

## ❗️Important Issue with Flow

The component works as it should but Flow has several complaints on the way `Tabs.Container` and all its subcomponents are being used.

To debug this I tried using the exact same code taken from the Tabs stories:

Screen Shot 2019-04-26 at 11 17 51 PM

 inside the `ListsEditor` component:

Screen Shot 2019-04-26 at 10 34 07 PM

I ran the flow typecheck and I'm getting the exact same errors even using the default usage from the Story for that component.

Screen Shot 2019-04-26 at 10 34 02 PM

So not only my usage fails but the exact same code from storybooks stories for that component fails the flow typecheck. I'm not sure if I should disable the flow typecheck for this one or how to fix these issues, so any help would be appreciated.

To reproduce this simply go to `src/components/ui/Tabs/Tabs.stories.js` copy the default example:
```
<Tabs.Container>
   <Tabs.Head tabKey='first'>
       <ExampleButton text='Tab 1' className='foo' />
   </Tabs.Head>
   <Tabs.Head tabKey='second'>
       <ExampleButton text='Tab 2' className='foo' />
    </Tabs.Head>
    <Tabs.Pane tabKey='first'>
        <div>Foo bar baz 1</div>
    </Tabs.Pane>
    <Tabs.Pane tabKey='second'>
       <div>Foo bar baz 2</div>
    </Tabs.Pane>
</Tabs.Container>

const ExampleButton = ({ isActive, text, ...props }) => {
  return (
    <span
      {...props}
      style={{ padding: '0 10px 10px 0' }}
      className={`${props.className ? `${props.className}` : ''}${isActive ? ' active' : ''}`}
    >
      {`${text}${isActive ? ' - I\'m active' : ''}`}
    </span>
  )
}
const HeadWrapper = props => <div className='header'>{props.children}</div>
const ContentWrapper = props => <div className='content'>{props.children}</div>
```

Try to run `npm run flow`

You should see the same warnings described above.

### CODE REVIEW

**Comment by nicksp** [comment]
@bernardorubin Could you please resolve merge conflicts on the PR?

**Comment by bernardorubin** [comment]
Still getting the same Flow error I mentioned previously:
Screen Shot 2019-05-07 at 12 11 04 PM

**Comment by nicksp** [comment]
@bernardorubin Ignore this for now please, this ticket isn't urgent. We can address it later.

**Comment by nicksp** [comment]
It's been inactive for a quite long time, so I'm gonna close it for the time being. We can reopen that or cherry-pick commits when needed.

**Pull request closed without merging**
