### PR TITLE
Add Counter component to Filters

### PR DESCRIPTION
**Pull request by Moharu**
**Release Type:** *Non-Breaking Feature*

Fixes https://x-team-internal.atlassian.net/browse/XP-3099

## Description

Counter component (simple label with coloring) to be used inside Filter headings.

## Checklist

- [x] set yourself as an assignee
- [x] set appropriate labels for a PR (`In Review` or `In Progress` depending on its status)
- [x] make sure your code lints (`npm run lint`)
- [x] Flow typechecks passed (`npm run flow`)
- [x] Snapshots tests passed (`npm run jest`)
- [x] if you've fixed a bug or added code that should be tested, add unit tests
- [x] if any snapshots have been changed, verify that component still works and looks as expected and update the changed snapshot
- [x] **manually tested the app** by running it in several different browsers (Firefox, Chrome, Opera, Safari, MS IE/Edge, etc.) and checked nothing is broken and operates as expected!

## Related PRs

branch | PR
------ | ------
XP-3099-add-counters-for-filters-and-results | [XP](https://github.com/x-team/xp/pull/1942)

## Steps to Test or Reproduce

Please refer to screenshot.

## Impacted Areas in Application

Filters component.

## Screenshots

xp3099labels

### CODE REVIEW

**Comment by nicksp** [comment]
Hey @Moharu Please check conflicting files at the bottom of PR

**Comment by Moharu** [comment]
Changed the base to "develop", but I guess git didn't like it lol
fixing it asap

**Comment by nicksp** [comment]
No problem, mate 😛 
The first two are usually get auto-fixed by running `npm run build` command.

**Comment by Moharu** [comment]
Hey @bernardodiasc and @nicksp , can you verify if https://github.com/x-team/xp-ui/pull/411/commits/6c1a14bf9fc49cc4461d2722953bdc9200610b59 is good, or anything else I should know/do differently? 😄

**Comment by nicksp** [comment]
> Hey @bernardodiasc and @nicksp , can you verify if 6c1a14b is good, or anything else I should know/do differently?

If you run `npm run build`, as I said before, and committed those rebuilt files, then this should be sufficient 😄

**Comment by Moharu** [comment]
> > Hey @bernardodiasc and @nicksp , can you verify if [6c1a14b](https://github.com/x-team/xp-ui/commit/6c1a14bf9fc49cc4461d2722953bdc9200610b59) is good, or anything else I should know/do differently?
> 
> If you run `npm run build`, as I said before, and committed those rebuilt files, then this should be sufficient 😄

Yeah, I think that's fixed, was asking about the implementation/code itself

**Comment by bernardodiasc** [comment]
@Moharu looks good to me. without having the art direction right away from designers that's good enough that we can do :)

**Comment by bernardodiasc** [comment]
@Moharu also, make sure to rebase this branch with latest `develop` 😉

**Pull request closed without merging**
