### PR TITLE
Add data-testid attribute needed for the E2E tests in the Search Page for the switching lists cases

### PR DESCRIPTION
**Pull request by kararade**
**Release Type:** *Non-Breaking Feature*

Fixes https://x-team-internal.atlassian.net/browse/XP-3170

## Description

- Added the `data-testid` attribute in the view of some components to be able to add the E2E required by the A/C

## Checklist

- [x] set yourself as an assignee
- [x] set appropriate labels for a PR
- [x] make sure your code lints (`npm run lint`)
- [x] Flow typechecks passed (`npm run flow`)
- [x] Snapshots tests passed (`npm run jest`)
- [x] if any snapshots have been changed, verify that component still works and looks as expected and update the changed snapshot

## Related PRs

branch | PR
------ | ------
XP-3170-e2e-switching-lists | [XP](https://github.com/x-team/xp/pull/1965)
XP-3171-switching-accepted-excluded | [XP](https://github.com/x-team/xp/pull/1966)
XP-3172-performing-filtering | [XP](https://github.com/x-team/xp/pull/1969)
XP-3173-updating-column-customizer | [XP](https://github.com/x-team/xp/pull/1971)
XP-3174-sorting-ordering | [XP](https://github.com/x-team/xp/pull/1970)
XP-3175-deleting-archiving | [XP](https://github.com/x-team/xp/pull/1972)
XP-3176-applicant-profile-view | [XP](https://github.com/x-team/xp/pull/1967)

## Impacted Areas in Application

- ApplicantBadge
- Button
- DataGrid
- HeadingWithQuickSearch
- Filters.Filter
- Filters.Group
- Filters.Label
- Filters.TabButton
- Filters.Heading
- ListsEditor
- QuickSearchButton

### CODE REVIEW

**Comment by nicksp** [comment]
Hey @kararade Is this really ready for review? I can see status is in progress, so wondering if we can test this ;-)

Also, could you please resolve merge conflicts on the ticket?

**Comment by kararade** [comment]
hey @nicksp I've fixed the conflicts, thanks!

**Comment by kararade** [comment]
hey @nicksp @bernardodiasc 
Remember to keep this PR on HOLD until getting all subtasks of this ticket were ready and merged in the XP project https://x-team-internal.atlassian.net/browse/XP-3166, please!
thanks!

**Comment by nicksp** [comment]
@kararade @bernardodiasc Guys, we don't have Prettier formatter bound to a git hook on this project, so I assume those changes might come from your local Prettier setup @kararade. I suggest you turn it off for all the xp projects in whatever editor you use and excplude those changes from the PR(s). Your local settings might be unsyched with [Standard JS](https://standardjs.com/rules.html) rules we follow.

I know, we could automate that as it's done in XP project, so might be a good clean up ticket idea 😏 Until it's done though, we should be careful with our local editors setup in order not to bring unwanted formatting changes.

**Comment by nicksp** [comment]
Hey @kararade Seems like we need to address these things before we can merge it, overall great work!:
- https://github.com/x-team/xp-ui/pull/423#pullrequestreview-272606092
- https://github.com/x-team/xp-ui/pull/423#issuecomment-519542411
- https://github.com/x-team/xp-ui/pull/423#pullrequestreview-272615980

**Comment by kararade** [comment]
> Hey @kararade Seems like we need to address these things before we can merge it, overall great work!:
> 
> * [#423 (review)](https://github.com/x-team/xp-ui/pull/423#pullrequestreview-272606092)
> * [#423 (comment)](https://github.com/x-team/xp-ui/pull/423#issuecomment-519542411)
> * [#423 (review)](https://github.com/x-team/xp-ui/pull/423#pullrequestreview-272615980)

Fixed all the related changes for the 3 comments

**Comment by nicksp** [comment]
@kararade Let's please remove formatting changes you introduced here if possible, so we can focus on relevant changes and not to introduce unwanted formatting statements.

**Comment by kararade** [comment]
Closed due to the high number of changes required to restore back the code style in this comment https://github.com/x-team/xp-ui/pull/423#issuecomment-520496017. Here you will find a new PR https://github.com/x-team/xp-ui/pull/425 with the same changes as this one but respecting the code style of the project

**Comment by nicksp** [comment]
@kararade Is it safe to also delete branch associated with a PR here?

**Comment by kararade** [comment]
@nicksp Yes, it is.

**Pull request closed without merging**
