### PR TITLE
Fix sizing issues with TwoColumnsLayout and Filters

### PR DESCRIPTION
**Pull request by bernardodiasc**
**Release Type:** *bug fix*

Fixes https://x-team-internal.atlassian.net/browse/XP-2845

## Description

This PR fixes some remaining issues with TwoColumnsLayout and Filters sizings.

## Checklist

- [x] set yourself as an assignee
- [x] set appropriate labels for a PR (`In Review` or `In Progress` depending on its status)
- [x] move respective JIRA issue to the `IN REVIEW` column
- [x] make sure your code lints (`npm run lint`)
- [x] Flow typechecks passed (`npm run flow`)
- [x] Snapshots tests passed (`npm run jest`)
- [x] component's documentation (`.stories.js` file) is changed or added accordingly to reflect any new or updated use cases or variants usage
- [x] if you've fixed a bug, make sure to also include a new story that will expose declarations with problematic data that caused the bug in the first place, so that we can assure that no regressions will pop up on future interactions
- [x] if any snapshots have been changed, verify that component still works and looks as expected and update the changed snapshot
- [x] **manually tested the app** by running it in several different browsers (Firefox, Chrome, Opera, Safari, MS IE/Edge, etc.) and checked nothing is broken and operates as expected!

## Steps to Test or Reproduce

1. run `npm start`
1. go to http://localhost:9001/?selectedKind=UI%20Components%2FTwoColumnsLayout%2FUse%20cases&selectedStory=composed%20in%20AdminScreen%20with%20Filters
1. resize the screen
    1. observe that the sidebar width are proportional to the screen width with value `30vw`
    1. observe how the sidebar adjusts to a maximum width of `385px`
    1. observe how the sidebar adjusts to a minimum width of `285px`

## Impacted Areas in Application

- `Filters/Filter.js`
- `Filters/Filters.stories.js`
- `Filters/Group.js`
- `Filters/Heading.js`
- `Filters/Label.js`
- `Filters/TabButton.js`
- `Filters/TabHeads.js`
- `TwoColumnsLayout.js`
- `TwoColumnsLayout.stories.js`

## Screenshots

screen shot 2019-02-21 at 11 04 56

### CODE REVIEW

**Comment by nicksp** [comment]
@bernardodiasc Please reopen this PR, it seems to be closed for some reasons.

**Comment by bernardodiasc** [comment]
I've based this branch pointing to `develop`, it was closed because `XP-2711-advanced-search-sprint-2` no longer exist. I'll reopen and add label `on hold` until we get the ticket in sprint.

**Comment by bernardodiasc** [comment]
Thanks for the review @galileo, I'll take the time to rebase once the ticket enters in the sprint, so that I spare from rebasing multiple times until that happen :)

**Comment by bernardodiasc** [comment]
I rebased this branch with latest develop and removed the `on hold` label. This should be ready to be reviewed now.

**Comment by nicksp** [comment]
@bernardodiasc Another UI regression I just found. We seem to affect List view with these changes and we didn't mean to do that. Only Advanced Search page was meant to be adjusted. The List UI on smaller screens now looks messy and kinda unusable in terms of readability. Instead of tweaking that, we should aim at impacting only AS.

image

**Comment by bernardodiasc** [comment]
@nicksp, based on your feedback, looks like we can't have a fluid and smaller width for the left column.  I'll revert changes related to that.

**Comment by bernardodiasc** [comment]
@nicksp I reverted the flexible width of the sidebar, during my tests the minimum width that fits well is just 40px less than the default, I'm not sure if that's an improvement after all. I believe the solution to have more space for the content is more on the collapsing effect direction. This PR contain many other fixes for the sidebar filters layout and improvements in the stories. Please let me know any concern.

**Comment by nicksp** [comment]
@bernardodiasc Tests on Travis and locally failing. Please take a look 
image

**Comment by nicksp** [comment]
@bernardodiasc Please also specify whether the ticket has breaking changes or not. Can't see it was set.

**Comment by bernardodiasc** [comment]
Good catch, I forgot to revert that. I should be good now.

**Pull request merged**
